# **[Python] - [Listas em Python]**
Plataforma: **DataCamp**

Data: **2026-06-16**

Status: **Em andamento**

## **📚 Objetivo desta aula**
**Aprender a criar listas ([]), para poder agrupar diferentes tipos de dados dentro de uma única variável e entender como acessar e manipular esses elementos.**

## **1️⃣ Conceito Teórico**

**O que é?**

Uma lista é uma estrutura que permite armazenar uma sequência de elementos (podendo ser de tipos diferentes) usando colchetes []. É uma coleção ordenada e mutável.

**Por quê aprender?**

Na análise de dados, quase nunca trabalhamos com um valor único. Listas permitem organizar conjuntos de observações, como uma lista de preços, nomes de produtos ou resultados de experimentos.

## **2️⃣ Exemplos da Aula**

In [1]:
# Listas em Python
fam = ['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam

['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [2]:
# Lista de listas

fam2 = fam = [['Liz', 1.73], 
              ['Emma', 1.68], 
              ['mom', 1.71], 
              ['dad', 1.89]]
fam2

[['Liz', 1.73], ['Emma', 1.68], ['mom', 1.71], ['dad', 1.89]]

**Dica importante:** 

Lembre-se sempre: em Python, a contagem começa no zero. O primeiro elemento da lista está no índice 0, o segundo no índice 1, e assim por diante. Se tentar acessar um índice que não existe, o Python emitirá um erro (IndexError).

# **Exercícios:**

Crie uma lista, areas, que contenha a área do corredor (hall), cozinha (kit), sala de estar (liv), quarto (bed) e banheiro (bath), nesta ordem. Use as variáveis predefinidas.
Imprima areas com a função print().

In [3]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Criando a lista areas

areas = [hall, kit, liv, bed, bath]

print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


Conclua o código que cria a lista areas. Crie a lista de modo que ela contenha primeiro o nome de cada cômodo como uma string e, em seguida, sua área. Em outras palavras, adicione as strings "hallway", "kitchen" e "bedroom" nos locais apropriados.
Imprima areas novamente; a impressão está mais informativa dessa vez?

In [5]:
# Criando a lista areas:

areas = ['hallway', hall, 'kitchen', kit, 'living room', liv, 'bedroom', bed, 'bathroom', bath]
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


Termine a lista de listas para que ela também contenha os dados do quarto (bedroom) e do banheiro (bathroom). Lembre-se de inseri-los em ordem!
Imprima house; essa forma de estruturar os dados faz mais sentido?


In [6]:
# Criando a lista de listas:

house = [
    ['hallway', hall],
    ['kichen', kit],
    ['living room', liv],
    ['bedroom', bed],
    ['bathroom', bath]
]

# printando house

print(house)

[['hallway', 11.25], ['kichen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


# **Subdivisão de Listas**

## **📚 Objetivo desta aula**

**Aprender a acessar informações de uma lista utilizando índice, sem precisar criar uma nova variável manualmente.**

## **1️⃣ Conceito Teórico**

**O que é?** 

O slicing permite acessar um intervalo de itens em uma lista usando a sintaxe lista[início : fim]. O número que você coloca no "início" é incluído, mas o número no "fim" é excluído.

**Por quê aprender?**

Crucial para manipulação de dados. Quando você tiver uma lista com 1.000 registros, poderá facilmente extrair apenas os primeiros 10, os últimos 5 ou qualquer intervalo específico necessário para sua análise.


## **2️⃣ Exemplos da Aula**

In [7]:
fam = ['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam

['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89]

## **[início : fim]**

In [8]:
fam[3]

1.68

In [9]:
fam[6]

'dad'

In [10]:
fam[-1]

1.89

In [11]:
fam[3:5]

[1.68, 'mom']

## **Exercícios:**

Imprima o segundo elemento da lista areas (ele tem o valor 11.25).

Crie um subconjunto e imprima o último elemento de areas, que é 9.50. Aqui faz sentido usar um índice negativo!

Selecione o número que representa a área da sala de estar (20.0) e imprima-o.


In [13]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

print(areas[1])

print(areas[-1])

print(areas[5])

11.25
9.5
20.0


Use o fatiamento para criar uma lista, downstairs, que contém os primeiros 6 elementos de areas.

Crie upstairs, com os últimos elementos de 4 de areas. Desta vez, simplifique o fatiamento omitindo o índice final (end).

Imprima downstairs e upstairs usando print().


In [14]:
downstairs = areas[:6]

upstairs = areas[-4:]

print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]



Uma lista Python também pode conter outras listas.

Para subdividir listas de listas, podemos usar a mesma técnica de antes: colchetes. 

Para uma lista chamada house, ficaria mais ou menos assim:

In [15]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

Subdivida a lista house para pegar o float 9.5

In [16]:
print(house[4][1])

9.5


# **Manipulação de listas**

Aprender a modificar, remover e alterar elementos dentro de uma lista existente para manter seus dados atualizados.

## **1️⃣ Conceito Teórico**

**O que é?**

Manipulação de listas envolve o uso de métodos (funções internas) para mudar o conteúdo de uma lista após ela já ter sido criada. Podemos substituir valores por índice, deletar itens ou trocar elementos de lugar.

**Por quê aprender?**

Em projetos reais, os dados chegam "sujos" ou incompletos. Você precisará constantemente atualizar valores errados, remover duplicatas ou inserir novas informações em listas que já existem.

In [17]:
# Lista Inicial
fam = ['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam

['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [19]:
# 1. Alterar um valor específico
fam[7] = 1.86
fam

['Liz', 1.73, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [21]:
# Alterando uma lista de listas
fam[0:2] = ['Lisa', 1.74]
fam

['Lisa', 1.74, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [23]:
# Incluindo elementos 
fam + ['me', 1.73]

['Lisa', 1.74, 'Emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.73]

In [24]:
# Excluindo elementos
del fam[2]
fam

['Lisa', 1.74, 1.68, 'mom', 1.71, 'dad', 1.86]

In [28]:
x = ['a', 'b', 'c']

y = x
y[1] = 'z'
y

['a', 'z', 'c']

In [29]:
x

['a', 'z', 'c']

In [32]:
# Copiando listas:

# Opção 1:
y = list(x)

# Opção 2:
y = x[:]

y[1] = 'z'
x

['a', 'z', 'c']

## **Exercícios**

Atualize a área do banheiro para 10.50 metros quadrados em vez de 9.50 usando indexação negativa.

Torne a lista areas mais moderna! Altere "living room" para "chill zone". Não use indexação negativa desta vez.


In [33]:
# Criando a lista de areas
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]


In [34]:
# Atualizando área do banheiro
areas[-1] = 10.50

In [35]:
# Alterando 'living room' para 'chill zone'
areas[4] = 'chill zone'

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


Você decide construir um anexo à piscina e uma garagem. Você pode adicionar as informações à lista areas?

Use o operador + para colar a lista ["poolhouse", 24.5] no final da lista areas. Armazene a lista resultante como areas_1.

Amplie ainda mais areas_1 adicionando dados sobre a garagem. Adicione a string "garage" e o float 15.45. Chame a lista resultante de areas_2.

In [36]:
# Adicionando poolhouse a nova lista
areas_1 = areas = ['poolhouse', 24.5]

# Adicionando garage à areas_1, na nova lista areas_2
areas_2 = areas_1 + ['garage', 15.45]

print(areas_1)
print(areas_2)

['poolhouse', 24.5]
['poolhouse', 24.5, 'garage', 15.45]


Apague a string e o float referentes a "poolhouse" na sua lista areas.

Imprima a lista atualizada areas.


In [37]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Deletando os itens poolhouse da lista
del areas[10:12]

# Imprimindo a lista atualizada
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


Altere o segundo comando, que cria a variável areas_copy, de modo que areas_copy seja uma cópia explícita de areas.

Após a edição, as alterações feitas em areas_copy não devem afetar areas. Envie a resposta para conferir.


In [38]:
# Criando a lista areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Alterando comando
areas_copy = areas[:]

# Alterando areas_copy
areas_copy[0] = 5.0

# Imprimindo areas
print(areas)
print(areas_copy)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]
